timezone: UTC
url: https://www.datasciencetweetsoftheday.ml
baseurl:
source: "."
destination: "./_site"
layouts_dir: _layouts
plugins_dir: _plugins
github:
 repo: https://github.com/ceshine/dstotd
data_dir: _data
includes_dir: _includes
theme: jekyll-theme-leap-day
title: Data Science Tweets of the Day
description: "Curated by <a href=\"https://twitter.com/ceshine_en\" class=\"desc\">@ceshine_en</a>. Inpired by <a href=\"https://twitter.com/wtfjht\" class=\"desc\">@WTFJHT</a>."
# Theme Options
show_downloads: false
# Paginate
paginate: 1
paginate_path: "/page/:num/"
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-archives
- amp-jekyll
ampdir: amp/
sass:
  sass_dir: _sass
  style: compressed
# SEO
logo: "/public/dstotd-wide.png"
twitter:
  username: ceshine_en
  card: summary
author:
  twitter: ceshine_en
  name: Ceshine Lee
  url: https://www.datasciencetweetsoftheday.ml
google_analytics: UA-24180048-5
# Collections
collections:
  posts:
    title: Posts
    output: true
    permalink: /posts/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
    values:
      type: posts
      image: "/public/dstotd-twitter.png"
# Archives
jekyll-archives:
  enabled:
  - year
  - month
  layouts:
    year: year-archive
    month: month-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
# Algolia
algolia:
  application_id: YLTA1XCGK6
  index_name: DSTOTD
  search_only_api_key: db0c5bd0fd28205f9100c3cf1520eb70
  nodes_to_index: "blockquote"
  files_to_exclude:
  - archive.html
  - atom.xml
  - index.html
  - rss.xml
  - page/*/*.html
  - posts/2018/5/20/day-1/*
  - _posts/2018-05-20-day-1.md
  - search.html
  settings:
    searchableAttributes:
    - content
    - headings
    - title
    - description
    distinct: true
