version: "3"
services:
  site:
    command: jekyll serve --watch
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    environment:
      - http_proxy=http://192.168.199.10:11233
      - https_proxy=http://192.168.199.10:11233
    ports:
      - 4000:4000
      # - 35729:35729
      # - 3000:3000
      # -   80:4000
